export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const SELECT_TASK = 'SELECT_TASK';
export const INCREMENT_TASK = 'INCREMENT_TASK';
export const REORDER_TASKS = 'REORDER_TASKS';

export const INCREMENT_FOCUSHOURS = 'INCREMENT_FOCUSHOURS';
export const NEW_WEEK = 'NEW_WEEK';

export const INCREMENT_STREAK = 'INCREMENT_STREAK';
export const UPDATE_LASTUSED_DATE = 'UPDATE_LASTUSED_DATE';
export const INCREMENT_DAYS_ACCESSED = 'INCREMENT_DAYS_ACCESSED';
export const RESET_STREAK = 'RESET_STREAK';
export const INCREMENT_TOTAL_FOCUSHOURS = 'INCREMENT_TOTAL_FOCUSHOURS';
