export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const SELECT_TASK = 'SELECT_TASK';
export const INCREMENT_TASK = 'INCREMENT_TASK';
export const REORDER_TASKS = 'REORDER_TASKS';

export const INCREMENT_FOCUSHOURS = 'INCREMENT_FOCUSHOURS';
export const DIFFERENT_DAY = 'DIFFERENT_DAY';
